### PR TITLE
MetaDefender Sandbox: Code style update - Rename OPSWAT Filescan Sandbox to MetaDefender Sandbox

### PR DESCRIPTION
**Pull request by anikobartos**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [X] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- OPSWAT Filescan Sandbox has been renamed in the early 2024 to MetaDefender Sandbox. 

image

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by anikobartos** [comment]
Hi @dvora-crest 
OPSWAT Filescan Sandbox is now MetaDefender Sandbox , but I can't change the app name since it is connected to the id, and I got this error:
FAILED - valid_app_name_and_guid  : Invalid GUID for app `Metadefender Sandbox`: GUID `6ad1c442-3bce-4df7-a0e2-4b4e1f3406fe` already maps to app `OPSWAT Filescan Sandbox`
Can you tell me how can I change the application name?
Thank you!

**Comment by anikobartos** [comment]
Hi @dvora-crest, @ishans-crest 
Could you help me with the issue mentioned above?

**Comment by mishalp-crest** [comment]
@anikobartos 
We have made some standard changes 
Let us know if you have doubt/concern
Meanwhile, we will take care of pipeline failures

**Comment by anikobartos** [comment]
> @anikobartos We have made some standard changes Let us know if you have doubt/concern Meanwhile, we will take care of pipeline failures

@mishalp-crest 
Thank you for the notification. 
Checked. I don't have any concern, and thanks the corrections!

**Review by hardik-crest — APPROVED** [review]

**Pull request merged**
