### PR TITLE
OPSWAT Filescan: New App - Initial submission

### PR DESCRIPTION
**Pull request by anikobartos**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [x] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [x] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
* Initial release with the following actions
    * detonate file
    * detonate url
    * search terms
    * file reputation
    * ip reputation
    * domain reputation
    * url reputation
    * test connectivity

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by anikobartos** [comment]
Hi @mpan-splunk ,
I have two remaining static test failure, but I don't know how can I solve it. 

1. The one is the missing appid:

_"Could not find an app id for opswatfilescan. Please add the app id for opswatfilescan to data/repo_name_to_appid.json"_
Exactly where should I enter my app id?

2. The other one is the _"File manipulation functions exist"_
I need to use file handling since I have a file detonation action, but I use vault_id for that. (That's what the documentation mentioned.) Did I miss something?

Thank you!

**Comment by mpan-splunk** [comment]
Hi @anikobartos , those issues will get taken care of when the PR is reviewed. Thxs!

**Comment by anikobartos** [comment]
> Hi @anikobartos , those issues will get taken care of when the PR is reviewed. Thxs!

Thank you @mpan-splunk ,
Could you please provide information regarding the procedure and timeline for reviewing pull requests? The timely publication of this integration holds significant importance for us. I would not like it if the acceptance was delayed because of me, and I would like to correct the errors as soon as possible if this is necessary.

**Comment by ishans-crest** [comment]
Hi @anikobartos 
We've started with the PR review. 
We'll take care of the remaining pipeline errors. Thanks for contributing! 
We'll keep you posted on the review progress.

**Comment by anikobartos** [comment]
Thank you @ishans-crest!

**Comment by anikobartos** [comment]
Hi @ishans-crest,
Any update? :)

**Comment by dvora-crest** [comment]
Hello @anikobartos 
We have stopped explicitly adding dependency for requests module , so could you please remove it from requirements.txt?
Thanks!

**Comment by anikobartos** [comment]
Hi @dvora-crest,
Thanks, I removed it.

**Comment by dvora-crest** [comment]
Hello @anikobartos,
We have updated the data_type for 'password' parameter in 'detonate file' and 'detonate url' actions from password to string as SOAR action parameters do not support password data_type and actions will fail in that case. However, if you do not want the password parameter to be simple string, you can move it to asset configuration parameters and keep it optional. 
Also, could you please test the app and let us know if it works for you?

**Comment by anikobartos** [comment]
Hi @dvora-crest,
Thanks for the correction! I tested it. It looks fine, and working as I expect.
The password parameter means the password of a zip file, so moving it to the asset configuration is not logical. 
So it's fine with simple string type.

**Review by mmomin-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Review by pdesai-crest — APPROVED** [review]

**Review by tonyc-phantom — APPROVED** [review]

**Comment by anikobartos** [comment]
Hi @tonyc-phantom,
I see that several people (included you) have already accepted my pull request. My question is, do you know when it will be merged? Furthermore, should I take any additional steps or provide any further assistance?"

**Comment by spopat-crest** [comment]
Hello @anikobartos, No further action is required from your end. Thanks.

**Review by splunk-jessica — APPROVED** [review]

**Pull request merged**
